# ##################################################
# #                                                #
# #    STACK ESCALABLE DE N8N PARA PRODUCCIÓN      #
# #         https://digitallfran.co                #
# #                                                #
# ##################################################

services:
  # --- El Cerebro de n8n (Editor, Webhooks, API) ---
  n8n_main:
    ## -----------------https://digitallfran.co--------------------- ##
    image: n8nio/n8n:latest
    container_name: n8n_main
    restart: unless-stopped
    command: start
    environment:
      - EXECUTIONS_PROCESS=main
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_HOST}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - N8N_HOST=${N8N_DOMAIN}
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://${N8N_DOMAIN}/
      - WEBHOOK_URL=https://${N8N_WEBHOOK_DOMAIN}/
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${TZ}
      - TZ=${TZ}
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=${QUEUE_HOST}
      - QUEUE_BULL_REDIS_PORT=${QUEUE_PORT}
      - QUEUE_BULL_REDIS_DB=${QUEUE_DB}
      - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD} # <-- LÍNEA AÑADIDA
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=${SMTP_HOST}
      - N8N_SMTP_PORT=${SMTP_PORT}
      - N8N_SMTP_USER=${SMTP_USER}
      - N8N_SMTP_PASS=${SMTP_PASS}
      - N8N_SMTP_SENDER=${SMTP_SENDER}
      - N8N_SMTP_SSL=${SMTP_SSL}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - digitallfran_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=digitallfran_net"
      - "traefik.http.routers.n8n-editor.rule=Host(`${N8N_DOMAIN}`)"
      - "traefik.http.routers.n8n-editor.entrypoints=websecure"
      - "traefik.http.routers.n8n-editor.tls.certresolver=myresolver"
      - "traefik.http.routers.n8n-editor.service=n8n_service"
      - "traefik.http.routers.n8n-webhook.rule=Host(`${N8N_WEBHOOK_DOMAIN}`)"
      - "traefik.http.routers.n8n-webhook.entrypoints=websecure"
      - "traefik.http.routers.n8n-webhook.tls.certresolver=myresolver"
      - "traefik.http.routers.n8n-webhook.service=n8n_service"
      - "traefik.http.services.n8n_service.loadbalancer.server.port=5678"

  # --- Los Brazos de n8n (Workers) ---
  n8n_worker:
    ## -----------------https://digitallfran.co--------------------- ##
    image: n8nio/n8n:latest
    container_name: n8n_worker
    restart: unless-stopped
    command: worker
    environment:
      - EXECUTIONS_PROCESS=worker
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_HOST}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${TZ}
      - TZ=${TZ}
      - QUEUE_BULL_REDIS_HOST=${QUEUE_HOST}
      - QUEUE_BULL_REDIS_PORT=${QUEUE_PORT}
      - QUEUE_BULL_REDIS_DB=${QUEUE_DB}
      - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD} # <-- LÍNEA AÑADIDA
      - N8N_WORKER_CONCURRENCY=10
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - digitallfran_net

volumes:
  n8n_data:

networks:
  digitallfran_net:
    external: true